
package org.pws.client.service_interaction_assets;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestProfilesWebStorageService", targetNamespace = "http://service.pws.org/", wsdlLocation = "http://desktop-n52kk1t:8089/ProfileWebService/TestProfilesWebStorageService?wsdl")
public class TestProfilesWebStorageService
    extends Service
{

    private final static URL TESTPROFILESWEBSTORAGESERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTPROFILESWEBSTORAGESERVICE_EXCEPTION;
    private final static QName TESTPROFILESWEBSTORAGESERVICE_QNAME = new QName("http://service.pws.org/", "TestProfilesWebStorageService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://desktop-n52kk1t:8089/ProfileWebService/TestProfilesWebStorageService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTPROFILESWEBSTORAGESERVICE_WSDL_LOCATION = url;
        TESTPROFILESWEBSTORAGESERVICE_EXCEPTION = e;
    }

    public TestProfilesWebStorageService() {
        super(__getWsdlLocation(), TESTPROFILESWEBSTORAGESERVICE_QNAME);
    }

    public TestProfilesWebStorageService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTPROFILESWEBSTORAGESERVICE_QNAME, features);
    }

    public TestProfilesWebStorageService(URL wsdlLocation) {
        super(wsdlLocation, TESTPROFILESWEBSTORAGESERVICE_QNAME);
    }

    public TestProfilesWebStorageService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTPROFILESWEBSTORAGESERVICE_QNAME, features);
    }

    public TestProfilesWebStorageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestProfilesWebStorageService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestProfilesWebStorage
     */
    @WebEndpoint(name = "TestProfilesWebStoragePort")
    public TestProfilesWebStorage getTestProfilesWebStoragePort() {
        return super.getPort(new QName("http://service.pws.org/", "TestProfilesWebStoragePort"), TestProfilesWebStorage.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestProfilesWebStorage
     */
    @WebEndpoint(name = "TestProfilesWebStoragePort")
    public TestProfilesWebStorage getTestProfilesWebStoragePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.pws.org/", "TestProfilesWebStoragePort"), TestProfilesWebStorage.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTPROFILESWEBSTORAGESERVICE_EXCEPTION!= null) {
            throw TESTPROFILESWEBSTORAGESERVICE_EXCEPTION;
        }
        return TESTPROFILESWEBSTORAGESERVICE_WSDL_LOCATION;
    }

}
